# Generated by Django 6.0.1 on 2026-01-27 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stripe_events',
            },
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_status_572d44_idx',
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('unpaid', 'Unpaid')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PREMIUM', 'Premium')], default='FREE', max_length=10),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['subscription_status'], name='subscriptio_subscri_ac2ead_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['stripe_customer_id'], name='subscriptio_stripe__84f275_idx'),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
    ]
